/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.validation;

import java.awt.Image;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author found404
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    
    
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Carga un archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Numero de telefono(entero)");

        jLabel2.setText("Ingresa un numero flotante");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton2.setText("Guardar en fichero");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Verificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Computacion tolerante a fallas");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(598, 598, 598)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(638, 638, 638))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(294, 294, 294))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean V(int f,String value){//Funcion para validar datos enteros y 
                                          // flotantes, recibe 0 si es entero y 
                                          //1 si es flotante, como segundo parametro
                                          //el string a validar para fialmente
                                          //retornar un voleano.
            String B;//Cadena que se validara
            int i,o;//Posicion en la cadena y vandera
            i=0;//iniciaizacion en la primera posicion
            B=value;//Asignacion de el String al String evaluado
            o=0;//Vandera se inicializa en 0 o como si cumple
            int token=0;//Variable para conteo de puntos en caso de ser flotante
            while(i<B.length()){//Bulce para recorrer la cadena
		if(f==0){//Si se pide validar un entero
                    if(B.charAt(i)>47 && B.charAt(i)<58)i++;//Si es un numero
                    else {//Si no es un numero
                            o=1;//No es un entero
                            break;//Terminamos con el recorrido de la cadena
                    }//FIn de si no es un numero
                }//Fin de validacion de entero
                
		if(f==1){//Si se pide validar un flotante
                    if(B.charAt(i)>47 && B.charAt(i)<58||B.charAt(i)=='.'){//SI es
                                                         //un numero o punto
                       if(token==1 && B.charAt(i)=='.'){//Si ya se registro un punto
                                                        //y se detecta otro
                          o=1;//No es un numero flotante
                          break;//termina el recorrido
                       }    
                       if(token==0 && B.charAt(i)=='.')//si es el primer punto
                           token=1;//Se registra que ya se encontro un punto
                       i++;//Incremento de posicion en la cadena
                    }//Fin de if en validacion de float 
                    else {//Si no es un numero ni un punto
                        o=1;//No es un flotante si no un caracter distinto
                        break;//Termina el recorrido de la cadena
                    }//Fin de no flotante
                }//Fin de if para validacion flotante
            }//FIn de recorrido de cadena
	if(o==1)//Si no cumple con el tipo de dato que se pide
            return false;//Retorno no cumple con el tipo de dato
        return true;//De loc contrario si cumple con el tipo de dato
}
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Evento del boton validar
        String num = jTextArea1.getText();//Captura del texto ingresado
        if(!V(0,num)|| num.length()==0)// Si no se ingresa un entero o si no se ingresa nada
            JOptionPane.showMessageDialog(this, num+" no es un entero, \n"//Mesaje de error, no 
                    + "1._ Evite poner espacios\n2._ Ingrese solo numeros enteros", "Error!",//es
                    JOptionPane.ERROR_MESSAGE);//un numero
        else{//De lo contrario significa que es un numero.
            ClassClient Client;//Creacion de objeto cliente
            RandomClient File;//Creacion de objeto para manejo de ficheros
            File = new RandomClient();//Inicializacion de objeto File
            Client = new ClassClient();//Inicializacion de objeto cliente
            Client.setUserName("Izmael21");//Seteo de nombre al objeto cliente
            Client.setTipeUser("Estudiante");//Seteo de tipo de usuario al objeto cliente
            Client.setStatus("Activo");//Seteo de estatus al objeto cliente
            Client.setName("Izmael");//Seteo de nombre al objeto cliente
            Client.setOneAPe("Guzman");//Seteo de primer apellido al objeto cliente
            Client.setTwoApe("Murguia");//Seteo del segundo apellido al objeto cliente
            Client.setId(Integer.parseInt(num));//Seteo de id al objeto cliente obtenido de
                                                //el campo de texto
            Client.setPassword("asdasdqw213dass");//Seteo de contrasena al objeto cliente
            Client.setAddress("Morelos 14");// Seteo de direccion al objeto cliente
            Client.setEmail("izmael.guzman4312@alumnos.udg.mx");//Seteo de email al objeto cliente
            Client.setPhone(12121);//Seteo de numero de telefono al objeto cliente
            try {//codigo a prueba de fallo
                File.AddEnd(Client);//Guardado del objeto en el fichero, posible fallo
                JOptionPane.showMessageDialog(this,"Objeto guardado correctamente con id = " + num);
                //Todo ok si se muestra el mensaje
            } catch (Exception ex) {//Ejecusion de instrucciones en caso de error
                JOptionPane.showMessageDialog(this, " Error con el fichero, el mensage de error es "
                        +ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
                //Mensaje informativo de error
            }//Fin de caso de error   
        }//Fin de numero valido
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String num = jTextArea2.getText();  
        
        if(!V(1,num) || num.length()==0 || num.equals("."))
            JOptionPane.showMessageDialog(this, num + " no es un flotante, \n1._ Evite poner espacios\n2._ Ingrese solon umeros con formto entero o flotante", "Error!", JOptionPane.ERROR_MESSAGE);
        else{
            double n = Double.parseDouble(num);
            JOptionPane.showMessageDialog(this,"Muy bien " + num +" es un numero flotante"+ String.valueOf(n));
        }
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser JFileChooser = new JFileChooser();//Obteto que nos permitira habrir un explorador de archivos
        FileNameExtensionFilter Filtred = new FileNameExtensionFilter("JPG,PNG,GIF & JPEG","jpg","png","gif","jpeg");//Filtro de tipo de archivos.
        JFileChooser.setFileFilter(Filtred);//Le aplicamos el filtro al explorador de archivos
        int RequestImage = JFileChooser.showOpenDialog(this);//Verificador de eleccion de archivos
        if(RequestImage == JFileChooser.APPROVE_OPTION){//Se compara si se selecciono algo o no
            String urlImage = JFileChooser.getSelectedFile().getPath();//Se obtiene la url de la imagen
            Image imageShow = new ImageIcon(urlImage).getImage();//Se crea la imagen con la url
            ImageIcon MyImage = new ImageIcon(imageShow.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH));//Se definen las                                                                                           //dimenciones y la escala
            jLabel3.setIcon(MyImage);//Se setea la imagen para que sea visible en la interfaz.
        }//Fin de caso de eleccion de imagen
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
                jLabel6.setText(null);
                Image imageShow = new ImageIcon("cucei.png").getImage();
                ImageIcon MyImage = new ImageIcon(imageShow.getScaledInstance(200,200, Image.SCALE_SMOOTH));
                jLabel6.setIcon(MyImage);
                
                jLabel5.setText(null);
                imageShow = new ImageIcon("udg.png").getImage();
                MyImage = new ImageIcon(imageShow.getScaledInstance(150,200, Image.SCALE_SMOOTH));
                jLabel5.setIcon(MyImage);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private static javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
